{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:11:38"}
{"level":"error","message":"Error in getUserRoles query: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:19:59"}
{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:19:59"}
{"level":"error","message":"Error in getUserRoles query: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error in getUserRoles query: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error in getUserRoles query: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:25"}
{"level":"error","message":"Error in getUserRoles query: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:26"}
{"level":"error","message":"Error getting user roles: Could not find a relationship between 'user_roles' and 'roles' in the schema cache","service":"lms-api","timestamp":"2025-05-21 22:25:26"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:30:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:42"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:42"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:43"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:43"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:44"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:44"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:44"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:31:44"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:17"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:17"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error fetching from user_roles table: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error getting user roles: relation \"public.user_roles\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:34:18"}
{"level":"error","message":"Error fetching user for roles: relation \"public.users\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:38:17"}
{"level":"error","message":"Error fetching user for roles: relation \"public.users\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:38:17"}
{"level":"error","message":"Error fetching user for roles: relation \"public.users\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:38:18"}
{"level":"error","message":"Error fetching user for roles: relation \"public.users\" does not exist","service":"lms-api","timestamp":"2025-05-21 22:38:18"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","service":"lms-api","timestamp":"2025-05-21 23:36:44"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","service":"lms-api","timestamp":"2025-05-21 23:37:56"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","service":"lms-api","timestamp":"2025-05-21 23:38:11"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","service":"lms-api","timestamp":"2025-05-22 00:10:31"}
{"level":"error","message":"Error connecting to MongoDB: connect ECONNREFUSED 127.0.0.1:27017","service":"lms-api","timestamp":"2025-05-22 00:13:12"}
{"level":"error","message":"Error connecting to MongoDB: Server selection timed out after 5000 ms","service":"lms-api","timestamp":"2025-05-22 00:54:28"}
{"level":"error","message":"Error getting user by ID: Socket 'secureConnect' timed out after 9999ms (connectTimeoutMS: 10000)","service":"lms-api","timestamp":"2025-05-22 01:06:55"}
{"level":"error","message":"JWT verification failed: Socket 'secureConnect' timed out after 9999ms (connectTimeoutMS: 10000)","service":"lms-api","timestamp":"2025-05-22 01:06:55"}
{"level":"error","message":"Error getting user by ID: Socket 'secureConnect' timed out after 10000ms (connectTimeoutMS: 10000)","service":"lms-api","timestamp":"2025-05-22 01:07:10"}
{"level":"error","message":"JWT verification failed: Socket 'secureConnect' timed out after 10000ms (connectTimeoutMS: 10000)","service":"lms-api","timestamp":"2025-05-22 01:07:10"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 02:55:14"}
{"level":"error","message":"Failed to connect to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:251:13)\n    at NativeConnection.openUri (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/connection.js:1071:34)\n    at Mongoose.connect (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/mongoose.js:450:15)\n    at connectToMongoDB (file:///home/mustakim/Desktop/LMS/backend/config/mongoClient.js:25:20)\n    at file:///home/mustakim/Desktop/LMS/backend/server.js:34:1\n    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)\n    at async loadESM (node:internal/process/esm_loader:34:7)\n    at async handleMainPromise (node:internal/modules/run_main:106:12)","timestamp":"2025-05-22 02:55:14"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 02:57:36"}
{"level":"error","message":"Failed to connect to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:251:13)\n    at NativeConnection.openUri (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/connection.js:1071:34)\n    at Mongoose.connect (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/mongoose.js:450:15)\n    at connectToMongoDB (file:///home/mustakim/Desktop/LMS/backend/config/mongoClient.js:25:20)\n    at file:///home/mustakim/Desktop/LMS/backend/server.js:34:1\n    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)\n    at async loadESM (node:internal/process/esm_loader:34:7)\n    at async handleMainPromise (node:internal/modules/run_main:106:12)","timestamp":"2025-05-22 02:57:36"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 02:58:56"}
{"level":"error","message":"Failed to connect to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:251:13)\n    at NativeConnection.openUri (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/connection.js:1071:34)\n    at Mongoose.connect (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/mongoose.js:450:15)\n    at connectToMongoDB (file:///home/mustakim/Desktop/LMS/backend/config/mongoClient.js:25:20)\n    at file:///home/mustakim/Desktop/LMS/backend/server.js:34:1\n    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)\n    at async loadESM (node:internal/process/esm_loader:34:7)\n    at async handleMainPromise (node:internal/modules/run_main:106:12)","timestamp":"2025-05-22 02:58:56"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 03:11:09"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 03:13:01"}
{"level":"error","message":"Error connecting to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","timestamp":"2025-05-22 03:41:52"}
{"level":"error","message":"Failed to connect to MongoDB: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections","service":"lms-api","stack":"MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections\n    at NativeConnection.createClient (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:251:13)\n    at NativeConnection.openUri (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/connection.js:1071:34)\n    at Mongoose.connect (/home/mustakim/Desktop/LMS/backend/node_modules/mongoose/lib/mongoose.js:450:15)\n    at connectToMongoDB (file:///home/mustakim/Desktop/LMS/backend/config/mongoClient.js:25:20)\n    at file:///home/mustakim/Desktop/LMS/backend/server.js:34:1\n    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)\n    at async loadESM (node:internal/process/esm_loader:34:7)\n    at async handleMainPromise (node:internal/modules/run_main:106:12)","timestamp":"2025-05-22 03:41:52"}
